version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: visitwitch-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - visitwitch-network

  backend:
    build: ./backend
    container_name: visitwitch-backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password@mongodb:27017/
      - DB_NAME=visitwitch
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
    depends_on:
      - mongodb
    networks:
      - visitwitch-network

  frontend:
    build: ./frontend
    container_name: visitwitch-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - visitwitch-network

volumes:
  mongodb_data:

networks:
  visitwitch-network:
    driver: bridge